services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom/n8n-nodes-fzap
    volumes:
      - n8n_data:/home/node/.n8n
      - .:/home/node/.n8n/custom/n8n-nodes-fzap

volumes:
  n8n_data:
